### ISSUE TITLE
How to add colors to the list?

### ISSUE THREAD

**Issue by CarterSnich** [Acolarh/colorgrab#13]
How can I add colors to the list? I added one, but I don't know what I did.

Hard to see, but I added a different color.
![image](https://github.com/nielssp/colorgrab/assets/52433531/1927953f-ad19-45bd-862c-55c2ade75e68)

**Comment by nielssp** [comment]
Right click while picking a color or inside the magnified area in the bottom right part of the window.

**Comment by CarterSnich** [comment]
Thanks!!!
