### ISSUE TITLE
Where do I get the proper wxwidgets?

### ISSUE THREAD

**Issue by RomanSC** [Acolarh/colorgrab#4]
The Wiki has no explanation as to what the proper packages to install are for Ubuntu to get wxwidgets, without wxwidgets cmake throws an error

Will suggest an edit to the wiki when I find out what the proper package in Ubuntu is

**Comment by RomanSC** [comment]
Found the dependencies in order to build at http://codelite.org/LiteEditor/WxWidgets30Binaries#toc2

Cmake successfully ran after I ran:

`sudo apt-get install libwxbase3.0-dev libwxgtk3.0-dev wx3.0-headers wx-common  wx3.0-i18n wx3.0-examples wx3.0-doc`

This did not make colorgrab executable, running still throws:

`colorgrab: command not found`

**Comment by nielssp** [comment]
After running `make`, you can run ColorGrab by running `./colorgrab`. The cmake-configuration does not currently include a generic install-command, so you will have to manually package it for your distribution, or copy the `colorgrab` executable to `/usr/bin`.

**Comment by RomanSC** [comment]
Awesome, thanks for the help. This is the my favorite color picker, so thanks for creating it
