### ISSUE TITLE
Doesn't work on multiple screen?

### ISSUE THREAD

**Issue by felixsanz** [Acolarh/colorgrab#6]
I'm using multiple screens and i'm also using i3 as my window manager. The thing is that colorgrab looks weird (unusable). It only shows half of both screens and seems like i can't move the zone to view the other parts of the screen, i can't zoom it out or anything, it's like stucked in that bugged zone.

Anyone can confirm it?

**Comment by nielssp** [comment]
Just tried it with i3 and two screens and I couldn't replicate the problem. I have previously seen some issues with multiple screens on Windows, although this sound a bit different.
How many screens do you use and how are they configured? Are they the same resolution? Could you provide a screenshot?

**Comment by felixsanz** [comment]
I'm going to try to explain my setup using ascii. Both screens are 1920x1200. My screen configuration is this:
```
            _____
 __________|     |
|     1    |  2  |
|__________|     |
           |_____|
```
So, one screen is horizontal and the other is vertical. This is my xrandr command:

```
xrandr \
    --output DVI-I-1 \
        --primary \
        --mode 1920x1200 \
        --pos 0x372 \
        --rotate normal \
    --output DVI-D-0 \
        --mode 1920x1200 \
        --pos 1920x0 \
        --rotate left
```

Both are same resolution as you can see.

I would provide a screenshot but it's really confusing when you look at it. What happens is that i only see 50% of the primary screen, and 50% of the secondary screen. Using ascii, this is the zone that appears:

```
          ___
     ____|      
      1  | 2 
     ____|      
         |___
```

**This is what renders inside colorgrab**. If you group the screens as if they were one, only the center of it appears.

Anything not drawed on this ascii doesn't appear inside colorgrab, so it's unusable.

To be more visual, this zones **doesn't** appear on colorgrab so i can't interact with them:

```
              ___
 ____            |
|   1         2  |
|____            |
              ___|
```

If i can provide some more feedback tell me.

EDIT: I've updated the ascii art because it was looking weird at first. Hope you can see it correctly.
