### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by wonea** [Acolarh/colorgrab#7]
I love using the tool on Windows 10, and often work at night. Is there any chance of a dark theme?

**Comment by nielssp** [comment]
Hi,
ColorGrab uses wxWidgets to draw its interface. On Windows it's compiled using wxMSW and thus uses native Windows widgets. Unfortunately I don't think it's possible to manually apply styling on top of those widgets.

I'll keep investigating though.

**Comment by nielssp** [comment]
Will probably eventually be supported by wxwidgets, https://github.com/wxWidgets/wxWidgets/issues/19352.
